name: ceiba_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.3
  hooks_riverpod: ^2.6.1
  retrofit: ^4.4.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  retrofit_generator: ^9.1.7
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
